apiVersion: v1
kind: Service
metadata:
  name: toleration-admission-controller
  namespace: kube-system
  labels:
    app: toleration-admission-controller
spec:
  selector:
    app: toleration-admission-controller
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP